x_path: /ix/djishnu/Akanksha/datasets/ERCC1_KO_mice/metacell/male_fast2b_2x_harmonyv2_X.csv
y_path: /ix/djishnu/Akanksha/datasets/ERCC1_KO_mice/metacell/male_fast2b_2x_harmonyv2_Y.csv
out_path: /ix/djishnu/Akanksha/datasets/ERCC1_KO_mice/metacell/slide_outs/male
delta:
  - 0.01
  - 0.1
lambda:
  - 0.5
  - 1
  - 0.1
spec: 0.2
y_factor: TRUE
y_levels:
  - 0
  - 1
eval_type: auc
SLIDE_iter: 1000
SLIDE_top_feats: 10
sampleCV_iter: 500
sampleCV_K: 4
do_interacts: TRUE
fdr: 0.1